/*
 * PlayPact API
 *
 * The API for PlayPact.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@playpact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using PlayPact.OpenAPI.Client;
using PlayPact.OpenAPI.Model;

namespace PlayPact.OpenAPI.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IReviewApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// TODO: Creates a report.
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createReviewDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void CreateReview(CreateReviewDto createReviewDto = default(CreateReviewDto), int operationIndex = 0);

        /// <summary>
        /// TODO: Creates a report.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createReviewDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> CreateReviewWithHttpInfo(CreateReviewDto createReviewDto = default(CreateReviewDto), int operationIndex = 0);
        /// <summary>
        /// Deletes a report.
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactUserId"> (optional)</param>
        /// <param name="playPactReview"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void DeleteMyReview(Guid? playPactUserId = default(Guid?), Guid? playPactReview = default(Guid?), int operationIndex = 0);

        /// <summary>
        /// Deletes a report.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactUserId"> (optional)</param>
        /// <param name="playPactReview"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteMyReviewWithHttpInfo(Guid? playPactUserId = default(Guid?), Guid? playPactReview = default(Guid?), int operationIndex = 0);
        /// <summary>
        /// Gets all reviews, including the user&#39;s review that will hold more information.
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactReportId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ReviewDto</returns>
        ReviewDto GetMyReview(Guid playPactReportId, int operationIndex = 0);

        /// <summary>
        /// Gets all reviews, including the user&#39;s review that will hold more information.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactReportId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ReviewDto</returns>
        ApiResponse<ReviewDto> GetMyReviewWithHttpInfo(Guid playPactReportId, int operationIndex = 0);
        /// <summary>
        /// Gets all reviews, including the user&#39;s review that will hold more information.
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactReportId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;ReviewDto&gt;</returns>
        List<ReviewDto> GetReviews(Guid playPactReportId, int operationIndex = 0);

        /// <summary>
        /// Gets all reviews, including the user&#39;s review that will hold more information.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactReportId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;ReviewDto&gt;</returns>
        ApiResponse<List<ReviewDto>> GetReviewsWithHttpInfo(Guid playPactReportId, int operationIndex = 0);
        /// <summary>
        /// Updates a report.
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactUserId"> (optional)</param>
        /// <param name="reviewDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void UpdateMyReview(Guid? playPactUserId = default(Guid?), ReviewDto reviewDto = default(ReviewDto), int operationIndex = 0);

        /// <summary>
        /// Updates a report.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactUserId"> (optional)</param>
        /// <param name="reviewDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> UpdateMyReviewWithHttpInfo(Guid? playPactUserId = default(Guid?), ReviewDto reviewDto = default(ReviewDto), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IReviewApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// TODO: Creates a report.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createReviewDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task CreateReviewAsync(CreateReviewDto createReviewDto = default(CreateReviewDto), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// TODO: Creates a report.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createReviewDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> CreateReviewWithHttpInfoAsync(CreateReviewDto createReviewDto = default(CreateReviewDto), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Deletes a report.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactUserId"> (optional)</param>
        /// <param name="playPactReview"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteMyReviewAsync(Guid? playPactUserId = default(Guid?), Guid? playPactReview = default(Guid?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Deletes a report.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactUserId"> (optional)</param>
        /// <param name="playPactReview"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteMyReviewWithHttpInfoAsync(Guid? playPactUserId = default(Guid?), Guid? playPactReview = default(Guid?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Gets all reviews, including the user&#39;s review that will hold more information.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactReportId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ReviewDto</returns>
        System.Threading.Tasks.Task<ReviewDto> GetMyReviewAsync(Guid playPactReportId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Gets all reviews, including the user&#39;s review that will hold more information.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactReportId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ReviewDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<ReviewDto>> GetMyReviewWithHttpInfoAsync(Guid playPactReportId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Gets all reviews, including the user&#39;s review that will hold more information.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactReportId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ReviewDto&gt;</returns>
        System.Threading.Tasks.Task<List<ReviewDto>> GetReviewsAsync(Guid playPactReportId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Gets all reviews, including the user&#39;s review that will hold more information.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactReportId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ReviewDto&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ReviewDto>>> GetReviewsWithHttpInfoAsync(Guid playPactReportId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Updates a report.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactUserId"> (optional)</param>
        /// <param name="reviewDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task UpdateMyReviewAsync(Guid? playPactUserId = default(Guid?), ReviewDto reviewDto = default(ReviewDto), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Updates a report.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactUserId"> (optional)</param>
        /// <param name="reviewDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> UpdateMyReviewWithHttpInfoAsync(Guid? playPactUserId = default(Guid?), ReviewDto reviewDto = default(ReviewDto), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IReviewApi : IReviewApiSync, IReviewApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ReviewApi : IReviewApi
    {
        private PlayPact.OpenAPI.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ReviewApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ReviewApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReviewApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ReviewApi(string basePath)
        {
            this.Configuration = PlayPact.OpenAPI.Client.Configuration.MergeConfigurations(
                PlayPact.OpenAPI.Client.GlobalConfiguration.Instance,
                new PlayPact.OpenAPI.Client.Configuration { BasePath = basePath }
            );
            this.Client = new PlayPact.OpenAPI.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new PlayPact.OpenAPI.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = PlayPact.OpenAPI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReviewApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ReviewApi(PlayPact.OpenAPI.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = PlayPact.OpenAPI.Client.Configuration.MergeConfigurations(
                PlayPact.OpenAPI.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new PlayPact.OpenAPI.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new PlayPact.OpenAPI.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = PlayPact.OpenAPI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReviewApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ReviewApi(PlayPact.OpenAPI.Client.ISynchronousClient client, PlayPact.OpenAPI.Client.IAsynchronousClient asyncClient, PlayPact.OpenAPI.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = PlayPact.OpenAPI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public PlayPact.OpenAPI.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public PlayPact.OpenAPI.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public PlayPact.OpenAPI.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public PlayPact.OpenAPI.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// TODO: Creates a report. 
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createReviewDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void CreateReview(CreateReviewDto createReviewDto = default(CreateReviewDto), int operationIndex = 0)
        {
            CreateReviewWithHttpInfo(createReviewDto);
        }

        /// <summary>
        /// TODO: Creates a report. 
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createReviewDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public PlayPact.OpenAPI.Client.ApiResponse<Object> CreateReviewWithHttpInfo(CreateReviewDto createReviewDto = default(CreateReviewDto), int operationIndex = 0)
        {
            PlayPact.OpenAPI.Client.RequestOptions localVarRequestOptions = new PlayPact.OpenAPI.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = PlayPact.OpenAPI.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = PlayPact.OpenAPI.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = createReviewDto;

            localVarRequestOptions.Operation = "ReviewApi.CreateReview";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/api/Review", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateReview", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// TODO: Creates a report. 
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createReviewDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task CreateReviewAsync(CreateReviewDto createReviewDto = default(CreateReviewDto), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await CreateReviewWithHttpInfoAsync(createReviewDto, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// TODO: Creates a report. 
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createReviewDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<PlayPact.OpenAPI.Client.ApiResponse<Object>> CreateReviewWithHttpInfoAsync(CreateReviewDto createReviewDto = default(CreateReviewDto), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            PlayPact.OpenAPI.Client.RequestOptions localVarRequestOptions = new PlayPact.OpenAPI.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = PlayPact.OpenAPI.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = PlayPact.OpenAPI.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = createReviewDto;

            localVarRequestOptions.Operation = "ReviewApi.CreateReview";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/api/Review", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateReview", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Deletes a report. 
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactUserId"> (optional)</param>
        /// <param name="playPactReview"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void DeleteMyReview(Guid? playPactUserId = default(Guid?), Guid? playPactReview = default(Guid?), int operationIndex = 0)
        {
            DeleteMyReviewWithHttpInfo(playPactUserId, playPactReview);
        }

        /// <summary>
        /// Deletes a report. 
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactUserId"> (optional)</param>
        /// <param name="playPactReview"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public PlayPact.OpenAPI.Client.ApiResponse<Object> DeleteMyReviewWithHttpInfo(Guid? playPactUserId = default(Guid?), Guid? playPactReview = default(Guid?), int operationIndex = 0)
        {
            PlayPact.OpenAPI.Client.RequestOptions localVarRequestOptions = new PlayPact.OpenAPI.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = PlayPact.OpenAPI.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = PlayPact.OpenAPI.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (playPactUserId != null)
            {
                localVarRequestOptions.QueryParameters.Add(PlayPact.OpenAPI.Client.ClientUtils.ParameterToMultiMap("", "playPactUserId", playPactUserId));
            }
            if (playPactReview != null)
            {
                localVarRequestOptions.QueryParameters.Add(PlayPact.OpenAPI.Client.ClientUtils.ParameterToMultiMap("", "playPactReview", playPactReview));
            }

            localVarRequestOptions.Operation = "ReviewApi.DeleteMyReview";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/api/Review", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteMyReview", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Deletes a report. 
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactUserId"> (optional)</param>
        /// <param name="playPactReview"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteMyReviewAsync(Guid? playPactUserId = default(Guid?), Guid? playPactReview = default(Guid?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await DeleteMyReviewWithHttpInfoAsync(playPactUserId, playPactReview, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Deletes a report. 
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactUserId"> (optional)</param>
        /// <param name="playPactReview"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<PlayPact.OpenAPI.Client.ApiResponse<Object>> DeleteMyReviewWithHttpInfoAsync(Guid? playPactUserId = default(Guid?), Guid? playPactReview = default(Guid?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            PlayPact.OpenAPI.Client.RequestOptions localVarRequestOptions = new PlayPact.OpenAPI.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = PlayPact.OpenAPI.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = PlayPact.OpenAPI.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (playPactUserId != null)
            {
                localVarRequestOptions.QueryParameters.Add(PlayPact.OpenAPI.Client.ClientUtils.ParameterToMultiMap("", "playPactUserId", playPactUserId));
            }
            if (playPactReview != null)
            {
                localVarRequestOptions.QueryParameters.Add(PlayPact.OpenAPI.Client.ClientUtils.ParameterToMultiMap("", "playPactReview", playPactReview));
            }

            localVarRequestOptions.Operation = "ReviewApi.DeleteMyReview";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/api/Review", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteMyReview", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets all reviews, including the user&#39;s review that will hold more information. 
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactReportId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ReviewDto</returns>
        public ReviewDto GetMyReview(Guid playPactReportId, int operationIndex = 0)
        {
            PlayPact.OpenAPI.Client.ApiResponse<ReviewDto> localVarResponse = GetMyReviewWithHttpInfo(playPactReportId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets all reviews, including the user&#39;s review that will hold more information. 
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactReportId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ReviewDto</returns>
        public PlayPact.OpenAPI.Client.ApiResponse<ReviewDto> GetMyReviewWithHttpInfo(Guid playPactReportId, int operationIndex = 0)
        {
            PlayPact.OpenAPI.Client.RequestOptions localVarRequestOptions = new PlayPact.OpenAPI.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = PlayPact.OpenAPI.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = PlayPact.OpenAPI.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("playPactReportId", PlayPact.OpenAPI.Client.ClientUtils.ParameterToString(playPactReportId)); // path parameter

            localVarRequestOptions.Operation = "ReviewApi.GetMyReview";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ReviewDto>("/api/Review/my/{playPactReportId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMyReview", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets all reviews, including the user&#39;s review that will hold more information. 
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactReportId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ReviewDto</returns>
        public async System.Threading.Tasks.Task<ReviewDto> GetMyReviewAsync(Guid playPactReportId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            PlayPact.OpenAPI.Client.ApiResponse<ReviewDto> localVarResponse = await GetMyReviewWithHttpInfoAsync(playPactReportId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets all reviews, including the user&#39;s review that will hold more information. 
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactReportId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ReviewDto)</returns>
        public async System.Threading.Tasks.Task<PlayPact.OpenAPI.Client.ApiResponse<ReviewDto>> GetMyReviewWithHttpInfoAsync(Guid playPactReportId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            PlayPact.OpenAPI.Client.RequestOptions localVarRequestOptions = new PlayPact.OpenAPI.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = PlayPact.OpenAPI.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = PlayPact.OpenAPI.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("playPactReportId", PlayPact.OpenAPI.Client.ClientUtils.ParameterToString(playPactReportId)); // path parameter

            localVarRequestOptions.Operation = "ReviewApi.GetMyReview";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<ReviewDto>("/api/Review/my/{playPactReportId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMyReview", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets all reviews, including the user&#39;s review that will hold more information. 
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactReportId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;ReviewDto&gt;</returns>
        public List<ReviewDto> GetReviews(Guid playPactReportId, int operationIndex = 0)
        {
            PlayPact.OpenAPI.Client.ApiResponse<List<ReviewDto>> localVarResponse = GetReviewsWithHttpInfo(playPactReportId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets all reviews, including the user&#39;s review that will hold more information. 
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactReportId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;ReviewDto&gt;</returns>
        public PlayPact.OpenAPI.Client.ApiResponse<List<ReviewDto>> GetReviewsWithHttpInfo(Guid playPactReportId, int operationIndex = 0)
        {
            PlayPact.OpenAPI.Client.RequestOptions localVarRequestOptions = new PlayPact.OpenAPI.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = PlayPact.OpenAPI.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = PlayPact.OpenAPI.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("playPactReportId", PlayPact.OpenAPI.Client.ClientUtils.ParameterToString(playPactReportId)); // path parameter

            localVarRequestOptions.Operation = "ReviewApi.GetReviews";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<ReviewDto>>("/api/Review/{playPactReportId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetReviews", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets all reviews, including the user&#39;s review that will hold more information. 
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactReportId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;ReviewDto&gt;</returns>
        public async System.Threading.Tasks.Task<List<ReviewDto>> GetReviewsAsync(Guid playPactReportId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            PlayPact.OpenAPI.Client.ApiResponse<List<ReviewDto>> localVarResponse = await GetReviewsWithHttpInfoAsync(playPactReportId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets all reviews, including the user&#39;s review that will hold more information. 
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactReportId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;ReviewDto&gt;)</returns>
        public async System.Threading.Tasks.Task<PlayPact.OpenAPI.Client.ApiResponse<List<ReviewDto>>> GetReviewsWithHttpInfoAsync(Guid playPactReportId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            PlayPact.OpenAPI.Client.RequestOptions localVarRequestOptions = new PlayPact.OpenAPI.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = PlayPact.OpenAPI.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = PlayPact.OpenAPI.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("playPactReportId", PlayPact.OpenAPI.Client.ClientUtils.ParameterToString(playPactReportId)); // path parameter

            localVarRequestOptions.Operation = "ReviewApi.GetReviews";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<ReviewDto>>("/api/Review/{playPactReportId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetReviews", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Updates a report. 
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactUserId"> (optional)</param>
        /// <param name="reviewDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void UpdateMyReview(Guid? playPactUserId = default(Guid?), ReviewDto reviewDto = default(ReviewDto), int operationIndex = 0)
        {
            UpdateMyReviewWithHttpInfo(playPactUserId, reviewDto);
        }

        /// <summary>
        /// Updates a report. 
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactUserId"> (optional)</param>
        /// <param name="reviewDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public PlayPact.OpenAPI.Client.ApiResponse<Object> UpdateMyReviewWithHttpInfo(Guid? playPactUserId = default(Guid?), ReviewDto reviewDto = default(ReviewDto), int operationIndex = 0)
        {
            PlayPact.OpenAPI.Client.RequestOptions localVarRequestOptions = new PlayPact.OpenAPI.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = PlayPact.OpenAPI.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = PlayPact.OpenAPI.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (playPactUserId != null)
            {
                localVarRequestOptions.QueryParameters.Add(PlayPact.OpenAPI.Client.ClientUtils.ParameterToMultiMap("", "playPactUserId", playPactUserId));
            }
            localVarRequestOptions.Data = reviewDto;

            localVarRequestOptions.Operation = "ReviewApi.UpdateMyReview";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<Object>("/api/Review", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateMyReview", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Updates a report. 
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactUserId"> (optional)</param>
        /// <param name="reviewDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task UpdateMyReviewAsync(Guid? playPactUserId = default(Guid?), ReviewDto reviewDto = default(ReviewDto), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await UpdateMyReviewWithHttpInfoAsync(playPactUserId, reviewDto, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Updates a report. 
        /// </summary>
        /// <exception cref="PlayPact.OpenAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playPactUserId"> (optional)</param>
        /// <param name="reviewDto"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<PlayPact.OpenAPI.Client.ApiResponse<Object>> UpdateMyReviewWithHttpInfoAsync(Guid? playPactUserId = default(Guid?), ReviewDto reviewDto = default(ReviewDto), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            PlayPact.OpenAPI.Client.RequestOptions localVarRequestOptions = new PlayPact.OpenAPI.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = PlayPact.OpenAPI.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = PlayPact.OpenAPI.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (playPactUserId != null)
            {
                localVarRequestOptions.QueryParameters.Add(PlayPact.OpenAPI.Client.ClientUtils.ParameterToMultiMap("", "playPactUserId", playPactUserId));
            }
            localVarRequestOptions.Data = reviewDto;

            localVarRequestOptions.Operation = "ReviewApi.UpdateMyReview";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PutAsync<Object>("/api/Review", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateMyReview", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
