/*
 * PlayPact API
 * The API for PlayPact.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@playpact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DashboardApi
 */
@Disabled
public class DashboardApiTest {

    private final DashboardApi api = new DashboardApi();

    /**
     * Gets the number of active reports.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getActiveReportsTest() throws ApiException {
        Integer response = api.getActiveReports();
        // TODO: test validations
    }

    /**
     * Gets the number of completed reports.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCompletedReportsTest() throws ApiException {
        Integer response = api.getCompletedReports();
        // TODO: test validations
    }

    /**
     * Gets the number of registered servers.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRegisteredServersTest() throws ApiException {
        Integer response = api.getRegisteredServers();
        // TODO: test validations
    }

    /**
     * Gets the number of users.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUserCountTest() throws ApiException {
        Integer response = api.getUserCount();
        // TODO: test validations
    }

}
