/*
 * PlayPact API
 * The API for PlayPact.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@playpact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ObjectionDto;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ObjectionApi
 */
@Disabled
public class ObjectionApiTest {

    private final ObjectionApi api = new ObjectionApi();

    /**
     * TODO: Creates a objection.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createObjectionTest() throws ApiException {
        ObjectionDto objectionDto = null;
        api.createObjection(objectionDto);
        // TODO: test validations
    }

    /**
     * TODO: Gets a objection.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getObjectionTest() throws ApiException {
        UUID playPactObjectionId = null;
        ObjectionDto response = api.getObjection(playPactObjectionId);
        // TODO: test validations
    }

    /**
     * TODO: Updates a objection.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateObjectionTest() throws ApiException {
        UUID playPactObjectionId = null;
        ObjectionDto objectionDto = null;
        api.updateObjection(playPactObjectionId, objectionDto);
        // TODO: test validations
    }

}
