/*
 * PlayPact API
 * The API for PlayPact.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@playpact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateObjectionDto
 */
public class CreateObjectionDtoTest {
    private final CreateObjectionDto model = new CreateObjectionDto();

    /**
     * Model tests for CreateObjectionDto
     */
    @Test
    public void testCreateObjectionDto() {
        // TODO: test CreateObjectionDto
    }

    /**
     * Test the property 'playPactObjectionId'
     */
    @Test
    public void playPactObjectionIdTest() {
        // TODO: test playPactObjectionId
    }

    /**
     * Test the property 'objection'
     */
    @Test
    public void objectionTest() {
        // TODO: test objection
    }

    /**
     * Test the property 'playPactSubjectId'
     */
    @Test
    public void playPactSubjectIdTest() {
        // TODO: test playPactSubjectId
    }

    /**
     * Test the property 'playPactReportId'
     */
    @Test
    public void playPactReportIdTest() {
        // TODO: test playPactReportId
    }

}
