/*
 * PlayPact API
 * The API for PlayPact.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@playpact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.client.model.FileType;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateEvidenceDto
 */
public class CreateEvidenceDtoTest {
    private final CreateEvidenceDto model = new CreateEvidenceDto();

    /**
     * Model tests for CreateEvidenceDto
     */
    @Test
    public void testCreateEvidenceDto() {
        // TODO: test CreateEvidenceDto
    }

    /**
     * Test the property 'playPactUploaderId'
     */
    @Test
    public void playPactUploaderIdTest() {
        // TODO: test playPactUploaderId
    }

    /**
     * Test the property 'playPactAttachedToId'
     */
    @Test
    public void playPactAttachedToIdTest() {
        // TODO: test playPactAttachedToId
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'fileType'
     */
    @Test
    public void fileTypeTest() {
        // TODO: test fileType
    }

    /**
     * Test the property 'blobStorageUri'
     */
    @Test
    public void blobStorageUriTest() {
        // TODO: test blobStorageUri
    }

}
