/*
 * PlayPact API
 * The API for PlayPact.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@playpact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.client.model.ReportStatus;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MyReportListDto
 */
public class MyReportListDtoTest {
    private final MyReportListDto model = new MyReportListDto();

    /**
     * Model tests for MyReportListDto
     */
    @Test
    public void testMyReportListDto() {
        // TODO: test MyReportListDto
    }

    /**
     * Test the property 'playPactReportId'
     */
    @Test
    public void playPactReportIdTest() {
        // TODO: test playPactReportId
    }

    /**
     * Test the property 'accusation'
     */
    @Test
    public void accusationTest() {
        // TODO: test accusation
    }

    /**
     * Test the property 'serverName'
     */
    @Test
    public void serverNameTest() {
        // TODO: test serverName
    }

    /**
     * Test the property 'subjectName'
     */
    @Test
    public void subjectNameTest() {
        // TODO: test subjectName
    }

    /**
     * Test the property 'reportStatus'
     */
    @Test
    public void reportStatusTest() {
        // TODO: test reportStatus
    }

}
