/*
 * PlayPact API
 *
 * The API for PlayPact.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@playpact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PlayPact.OpenAPI.Model;
using PlayPact.OpenAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PlayPact.OpenAPI.Test.Model
{
    /// <summary>
    ///  Class for testing CreateMyReportDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateMyReportDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateMyReportDto
        //private CreateMyReportDto instance;

        public CreateMyReportDtoTests()
        {
            // TODO uncomment below to create an instance of CreateMyReportDto
            //instance = new CreateMyReportDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateMyReportDto
        /// </summary>
        [Fact]
        public void CreateMyReportDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateMyReportDto
            //Assert.IsType<CreateMyReportDto>(instance);
        }

        /// <summary>
        /// Test the property 'Accusation'
        /// </summary>
        [Fact]
        public void AccusationTest()
        {
            // TODO unit test for the property 'Accusation'
        }

        /// <summary>
        /// Test the property 'PlayPactCreatorId'
        /// </summary>
        [Fact]
        public void PlayPactCreatorIdTest()
        {
            // TODO unit test for the property 'PlayPactCreatorId'
        }

        /// <summary>
        /// Test the property 'PlayPactSubjectId'
        /// </summary>
        [Fact]
        public void PlayPactSubjectIdTest()
        {
            // TODO unit test for the property 'PlayPactSubjectId'
        }

        /// <summary>
        /// Test the property 'Rules'
        /// </summary>
        [Fact]
        public void RulesTest()
        {
            // TODO unit test for the property 'Rules'
        }

        /// <summary>
        /// Test the property 'PlayPactServerId'
        /// </summary>
        [Fact]
        public void PlayPactServerIdTest()
        {
            // TODO unit test for the property 'PlayPactServerId'
        }

        /// <summary>
        /// Test the property 'Evidence'
        /// </summary>
        [Fact]
        public void EvidenceTest()
        {
            // TODO unit test for the property 'Evidence'
        }
    }
}
