/*
 * PlayPact API
 *
 * The API for PlayPact.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@playpact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PlayPact.OpenAPI.Model;
using PlayPact.OpenAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PlayPact.OpenAPI.Test.Model
{
    /// <summary>
    ///  Class for testing CreateEvidenceDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateEvidenceDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateEvidenceDto
        //private CreateEvidenceDto instance;

        public CreateEvidenceDtoTests()
        {
            // TODO uncomment below to create an instance of CreateEvidenceDto
            //instance = new CreateEvidenceDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateEvidenceDto
        /// </summary>
        [Fact]
        public void CreateEvidenceDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateEvidenceDto
            //Assert.IsType<CreateEvidenceDto>(instance);
        }

        /// <summary>
        /// Test the property 'PlayPactUploaderId'
        /// </summary>
        [Fact]
        public void PlayPactUploaderIdTest()
        {
            // TODO unit test for the property 'PlayPactUploaderId'
        }

        /// <summary>
        /// Test the property 'PlayPactAttachedToId'
        /// </summary>
        [Fact]
        public void PlayPactAttachedToIdTest()
        {
            // TODO unit test for the property 'PlayPactAttachedToId'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'FileType'
        /// </summary>
        [Fact]
        public void FileTypeTest()
        {
            // TODO unit test for the property 'FileType'
        }

        /// <summary>
        /// Test the property 'BlobStorageUri'
        /// </summary>
        [Fact]
        public void BlobStorageUriTest()
        {
            // TODO unit test for the property 'BlobStorageUri'
        }
    }
}
