/*
 * PlayPact API
 *
 * The API for PlayPact.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@playpact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PlayPact.OpenAPI.Model;
using PlayPact.OpenAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PlayPact.OpenAPI.Test.Model
{
    /// <summary>
    ///  Class for testing EvidenceListDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EvidenceListDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EvidenceListDto
        //private EvidenceListDto instance;

        public EvidenceListDtoTests()
        {
            // TODO uncomment below to create an instance of EvidenceListDto
            //instance = new EvidenceListDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EvidenceListDto
        /// </summary>
        [Fact]
        public void EvidenceListDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" EvidenceListDto
            //Assert.IsType<EvidenceListDto>(instance);
        }

        /// <summary>
        /// Test the property 'PlayPactEvidenceId'
        /// </summary>
        [Fact]
        public void PlayPactEvidenceIdTest()
        {
            // TODO unit test for the property 'PlayPactEvidenceId'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'FileType'
        /// </summary>
        [Fact]
        public void FileTypeTest()
        {
            // TODO unit test for the property 'FileType'
        }

        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Fact]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
    }
}
