/*
 * PlayPact API
 *
 * The API for PlayPact.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@playpact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PlayPact.OpenAPI.Model;
using PlayPact.OpenAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PlayPact.OpenAPI.Test.Model
{
    /// <summary>
    ///  Class for testing ReportListDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReportListDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReportListDto
        //private ReportListDto instance;

        public ReportListDtoTests()
        {
            // TODO uncomment below to create an instance of ReportListDto
            //instance = new ReportListDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReportListDto
        /// </summary>
        [Fact]
        public void ReportListDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReportListDto
            //Assert.IsType<ReportListDto>(instance);
        }

        /// <summary>
        /// Test the property 'PlayPactReportId'
        /// </summary>
        [Fact]
        public void PlayPactReportIdTest()
        {
            // TODO unit test for the property 'PlayPactReportId'
        }

        /// <summary>
        /// Test the property 'Accusation'
        /// </summary>
        [Fact]
        public void AccusationTest()
        {
            // TODO unit test for the property 'Accusation'
        }

        /// <summary>
        /// Test the property 'ServerName'
        /// </summary>
        [Fact]
        public void ServerNameTest()
        {
            // TODO unit test for the property 'ServerName'
        }
    }
}
