/*
 * PlayPact API
 *
 * The API for PlayPact.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@playpact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PlayPact.OpenAPI.Model;
using PlayPact.OpenAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PlayPact.OpenAPI.Test.Model
{
    /// <summary>
    ///  Class for testing RuleListDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RuleListDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RuleListDto
        //private RuleListDto instance;

        public RuleListDtoTests()
        {
            // TODO uncomment below to create an instance of RuleListDto
            //instance = new RuleListDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RuleListDto
        /// </summary>
        [Fact]
        public void RuleListDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" RuleListDto
            //Assert.IsType<RuleListDto>(instance);
        }

        /// <summary>
        /// Test the property 'PlayPactRuleId'
        /// </summary>
        [Fact]
        public void PlayPactRuleIdTest()
        {
            // TODO unit test for the property 'PlayPactRuleId'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
    }
}
