/*
 * PlayPact API
 * The API for PlayPact.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@playpact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * VerdictListDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-27T21:45:49.723319836Z[Etc/UTC]", comments = "Generator version: 7.6.0-SNAPSHOT")
public class VerdictListDto {
  public static final String SERIALIZED_NAME_PLAY_PACT_REPORT_ID = "playPactReportId";
  @SerializedName(SERIALIZED_NAME_PLAY_PACT_REPORT_ID)
  private UUID playPactReportId;

  public static final String SERIALIZED_NAME_ACCUSATION = "accusation";
  @SerializedName(SERIALIZED_NAME_ACCUSATION)
  private String accusation;

  public static final String SERIALIZED_NAME_SERVER_NAME = "serverName";
  @SerializedName(SERIALIZED_NAME_SERVER_NAME)
  private String serverName;

  public VerdictListDto() {
  }

  public VerdictListDto playPactReportId(UUID playPactReportId) {
    this.playPactReportId = playPactReportId;
    return this;
  }

   /**
   * Get playPactReportId
   * @return playPactReportId
  **/
  @javax.annotation.Nullable
  public UUID getPlayPactReportId() {
    return playPactReportId;
  }

  public void setPlayPactReportId(UUID playPactReportId) {
    this.playPactReportId = playPactReportId;
  }


  public VerdictListDto accusation(String accusation) {
    this.accusation = accusation;
    return this;
  }

   /**
   * Get accusation
   * @return accusation
  **/
  @javax.annotation.Nullable
  public String getAccusation() {
    return accusation;
  }

  public void setAccusation(String accusation) {
    this.accusation = accusation;
  }


  public VerdictListDto serverName(String serverName) {
    this.serverName = serverName;
    return this;
  }

   /**
   * Get serverName
   * @return serverName
  **/
  @javax.annotation.Nullable
  public String getServerName() {
    return serverName;
  }

  public void setServerName(String serverName) {
    this.serverName = serverName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerdictListDto verdictListDto = (VerdictListDto) o;
    return Objects.equals(this.playPactReportId, verdictListDto.playPactReportId) &&
        Objects.equals(this.accusation, verdictListDto.accusation) &&
        Objects.equals(this.serverName, verdictListDto.serverName);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(playPactReportId, accusation, serverName);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerdictListDto {\n");
    sb.append("    playPactReportId: ").append(toIndentedString(playPactReportId)).append("\n");
    sb.append("    accusation: ").append(toIndentedString(accusation)).append("\n");
    sb.append("    serverName: ").append(toIndentedString(serverName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("playPactReportId");
    openapiFields.add("accusation");
    openapiFields.add("serverName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to VerdictListDto
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!VerdictListDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in VerdictListDto is not found in the empty JSON string", VerdictListDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!VerdictListDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `VerdictListDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("playPactReportId") != null && !jsonObj.get("playPactReportId").isJsonNull()) && !jsonObj.get("playPactReportId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `playPactReportId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("playPactReportId").toString()));
      }
      if ((jsonObj.get("accusation") != null && !jsonObj.get("accusation").isJsonNull()) && !jsonObj.get("accusation").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `accusation` to be a primitive type in the JSON string but got `%s`", jsonObj.get("accusation").toString()));
      }
      if ((jsonObj.get("serverName") != null && !jsonObj.get("serverName").isJsonNull()) && !jsonObj.get("serverName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `serverName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("serverName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VerdictListDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VerdictListDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VerdictListDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VerdictListDto.class));

       return (TypeAdapter<T>) new TypeAdapter<VerdictListDto>() {
           @Override
           public void write(JsonWriter out, VerdictListDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public VerdictListDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of VerdictListDto given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of VerdictListDto
  * @throws IOException if the JSON string is invalid with respect to VerdictListDto
  */
  public static VerdictListDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VerdictListDto.class);
  }

 /**
  * Convert an instance of VerdictListDto to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

