/*
 * PlayPact API
 * The API for PlayPact.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@playpact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * PlatformIdentifierDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-04T20:15:52.211240843Z[Etc/UTC]")
public class PlatformIdentifierDto {
  public static final String SERIALIZED_NAME_STEAM_ID = "steamId";
  @SerializedName(SERIALIZED_NAME_STEAM_ID)
  private String steamId;

  public static final String SERIALIZED_NAME_MINECRAFT_ID = "minecraftId";
  @SerializedName(SERIALIZED_NAME_MINECRAFT_ID)
  private String minecraftId;

  public static final String SERIALIZED_NAME_ROCKSTAR_ID = "rockstarId";
  @SerializedName(SERIALIZED_NAME_ROCKSTAR_ID)
  private String rockstarId;

  public static final String SERIALIZED_NAME_EPIC_GAMES_ID = "epicGamesId";
  @SerializedName(SERIALIZED_NAME_EPIC_GAMES_ID)
  private String epicGamesId;

  public PlatformIdentifierDto() {
  }

  public PlatformIdentifierDto steamId(String steamId) {
    this.steamId = steamId;
    return this;
  }

   /**
   * Get steamId
   * @return steamId
  **/
  @javax.annotation.Nullable
  public String getSteamId() {
    return steamId;
  }

  public void setSteamId(String steamId) {
    this.steamId = steamId;
  }


  public PlatformIdentifierDto minecraftId(String minecraftId) {
    this.minecraftId = minecraftId;
    return this;
  }

   /**
   * Get minecraftId
   * @return minecraftId
  **/
  @javax.annotation.Nullable
  public String getMinecraftId() {
    return minecraftId;
  }

  public void setMinecraftId(String minecraftId) {
    this.minecraftId = minecraftId;
  }


  public PlatformIdentifierDto rockstarId(String rockstarId) {
    this.rockstarId = rockstarId;
    return this;
  }

   /**
   * Get rockstarId
   * @return rockstarId
  **/
  @javax.annotation.Nullable
  public String getRockstarId() {
    return rockstarId;
  }

  public void setRockstarId(String rockstarId) {
    this.rockstarId = rockstarId;
  }


  public PlatformIdentifierDto epicGamesId(String epicGamesId) {
    this.epicGamesId = epicGamesId;
    return this;
  }

   /**
   * Get epicGamesId
   * @return epicGamesId
  **/
  @javax.annotation.Nullable
  public String getEpicGamesId() {
    return epicGamesId;
  }

  public void setEpicGamesId(String epicGamesId) {
    this.epicGamesId = epicGamesId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlatformIdentifierDto platformIdentifierDto = (PlatformIdentifierDto) o;
    return Objects.equals(this.steamId, platformIdentifierDto.steamId) &&
        Objects.equals(this.minecraftId, platformIdentifierDto.minecraftId) &&
        Objects.equals(this.rockstarId, platformIdentifierDto.rockstarId) &&
        Objects.equals(this.epicGamesId, platformIdentifierDto.epicGamesId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(steamId, minecraftId, rockstarId, epicGamesId);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlatformIdentifierDto {\n");
    sb.append("    steamId: ").append(toIndentedString(steamId)).append("\n");
    sb.append("    minecraftId: ").append(toIndentedString(minecraftId)).append("\n");
    sb.append("    rockstarId: ").append(toIndentedString(rockstarId)).append("\n");
    sb.append("    epicGamesId: ").append(toIndentedString(epicGamesId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("steamId");
    openapiFields.add("minecraftId");
    openapiFields.add("rockstarId");
    openapiFields.add("epicGamesId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PlatformIdentifierDto
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PlatformIdentifierDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PlatformIdentifierDto is not found in the empty JSON string", PlatformIdentifierDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PlatformIdentifierDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PlatformIdentifierDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("steamId") != null && !jsonObj.get("steamId").isJsonNull()) && !jsonObj.get("steamId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `steamId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("steamId").toString()));
      }
      if ((jsonObj.get("minecraftId") != null && !jsonObj.get("minecraftId").isJsonNull()) && !jsonObj.get("minecraftId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `minecraftId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("minecraftId").toString()));
      }
      if ((jsonObj.get("rockstarId") != null && !jsonObj.get("rockstarId").isJsonNull()) && !jsonObj.get("rockstarId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `rockstarId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rockstarId").toString()));
      }
      if ((jsonObj.get("epicGamesId") != null && !jsonObj.get("epicGamesId").isJsonNull()) && !jsonObj.get("epicGamesId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `epicGamesId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("epicGamesId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PlatformIdentifierDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PlatformIdentifierDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PlatformIdentifierDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PlatformIdentifierDto.class));

       return (TypeAdapter<T>) new TypeAdapter<PlatformIdentifierDto>() {
           @Override
           public void write(JsonWriter out, PlatformIdentifierDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PlatformIdentifierDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PlatformIdentifierDto given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PlatformIdentifierDto
  * @throws IOException if the JSON string is invalid with respect to PlatformIdentifierDto
  */
  public static PlatformIdentifierDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PlatformIdentifierDto.class);
  }

 /**
  * Convert an instance of PlatformIdentifierDto to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

