/*
 * PlayPact API
 * The API for PlayPact.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@playpact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.PactPointReportTransactionDto;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PactPointApi
 */
@Disabled
public class PactPointApiTest {

    private final PactPointApi api = new PactPointApi();

    /**
     * TODO: Gets a pact point transaction.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPactPointTransactionTest() throws ApiException {
        UUID playPactTransactionId = null;
        PactPointReportTransactionDto response = api.getPactPointTransaction(playPactTransactionId);
        // TODO: test validations
    }

    /**
     * TODO: Gets all pact point transactions.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPactPointTransactionsTest() throws ApiException {
        List<PactPointReportTransactionDto> response = api.getPactPointTransactions();
        // TODO: test validations
    }

}
