/*
 * PlayPact API
 *
 * The API for PlayPact.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@playpact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CreateObjectionDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateObjectionDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateObjectionDto
        //private CreateObjectionDto instance;

        public CreateObjectionDtoTests()
        {
            // TODO uncomment below to create an instance of CreateObjectionDto
            //instance = new CreateObjectionDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateObjectionDto
        /// </summary>
        [Fact]
        public void CreateObjectionDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateObjectionDto
            //Assert.IsType<CreateObjectionDto>(instance);
        }

        /// <summary>
        /// Test the property 'PlayPactObjectionId'
        /// </summary>
        [Fact]
        public void PlayPactObjectionIdTest()
        {
            // TODO unit test for the property 'PlayPactObjectionId'
        }

        /// <summary>
        /// Test the property 'Objection'
        /// </summary>
        [Fact]
        public void ObjectionTest()
        {
            // TODO unit test for the property 'Objection'
        }

        /// <summary>
        /// Test the property 'PlayPactSubjectId'
        /// </summary>
        [Fact]
        public void PlayPactSubjectIdTest()
        {
            // TODO unit test for the property 'PlayPactSubjectId'
        }

        /// <summary>
        /// Test the property 'PlayPactReportId'
        /// </summary>
        [Fact]
        public void PlayPactReportIdTest()
        {
            // TODO unit test for the property 'PlayPactReportId'
        }
    }
}
