/*
 * PlayPact API
 *
 * The API for PlayPact.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@playpact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CreateRuleDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateRuleDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateRuleDto
        //private CreateRuleDto instance;

        public CreateRuleDtoTests()
        {
            // TODO uncomment below to create an instance of CreateRuleDto
            //instance = new CreateRuleDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateRuleDto
        /// </summary>
        [Fact]
        public void CreateRuleDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateRuleDto
            //Assert.IsType<CreateRuleDto>(instance);
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Penalty'
        /// </summary>
        [Fact]
        public void PenaltyTest()
        {
            // TODO unit test for the property 'Penalty'
        }
    }
}
