/*
 * PlayPact API
 *
 * The API for PlayPact.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@playpact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PactPointReportTransactionDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PactPointReportTransactionDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PactPointReportTransactionDto
        //private PactPointReportTransactionDto instance;

        public PactPointReportTransactionDtoTests()
        {
            // TODO uncomment below to create an instance of PactPointReportTransactionDto
            //instance = new PactPointReportTransactionDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PactPointReportTransactionDto
        /// </summary>
        [Fact]
        public void PactPointReportTransactionDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PactPointReportTransactionDto
            //Assert.IsType<PactPointReportTransactionDto>(instance);
        }

        /// <summary>
        /// Test the property 'PlayPactServerId'
        /// </summary>
        [Fact]
        public void PlayPactServerIdTest()
        {
            // TODO unit test for the property 'PlayPactServerId'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
    }
}
