/*
 * PlayPact API
 *
 * The API for PlayPact.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@playpact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PactPointHistoryDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PactPointHistoryDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PactPointHistoryDto
        //private PactPointHistoryDto instance;

        public PactPointHistoryDtoTests()
        {
            // TODO uncomment below to create an instance of PactPointHistoryDto
            //instance = new PactPointHistoryDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PactPointHistoryDto
        /// </summary>
        [Fact]
        public void PactPointHistoryDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PactPointHistoryDto
            //Assert.IsType<PactPointHistoryDto>(instance);
        }

        /// <summary>
        /// Test the property 'PactPoints'
        /// </summary>
        [Fact]
        public void PactPointsTest()
        {
            // TODO unit test for the property 'PactPoints'
        }

        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
    }
}
