/*
 * PlayPact API
 *
 * The API for PlayPact.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@playpact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CreateReviewDto
    /// </summary>
    [DataContract(Name = "CreateReviewDto")]
    public partial class CreateReviewDto : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Evaluation
        /// </summary>
        [DataMember(Name = "evaluation", EmitDefaultValue = false)]
        public ReviewEvaluation? Evaluation { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateReviewDto" /> class.
        /// </summary>
        /// <param name="playPactCreatorId">playPactCreatorId.</param>
        /// <param name="playPactReportId">playPactReportId.</param>
        /// <param name="reason">reason.</param>
        /// <param name="rules">rules.</param>
        /// <param name="evaluation">evaluation.</param>
        public CreateReviewDto(Guid playPactCreatorId = default(Guid), Guid playPactReportId = default(Guid), string reason = default(string), List<RuleListDto> rules = default(List<RuleListDto>), ReviewEvaluation? evaluation = default(ReviewEvaluation?))
        {
            this.PlayPactCreatorId = playPactCreatorId;
            this.PlayPactReportId = playPactReportId;
            this.Reason = reason;
            this.Rules = rules;
            this.Evaluation = evaluation;
        }

        /// <summary>
        /// Gets or Sets PlayPactCreatorId
        /// </summary>
        [DataMember(Name = "playPactCreatorId", EmitDefaultValue = false)]
        public Guid PlayPactCreatorId { get; set; }

        /// <summary>
        /// Gets or Sets PlayPactReportId
        /// </summary>
        [DataMember(Name = "playPactReportId", EmitDefaultValue = false)]
        public Guid PlayPactReportId { get; set; }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        [DataMember(Name = "reason", EmitDefaultValue = true)]
        public string Reason { get; set; }

        /// <summary>
        /// Gets or Sets Rules
        /// </summary>
        [DataMember(Name = "rules", EmitDefaultValue = true)]
        public List<RuleListDto> Rules { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateReviewDto {\n");
            sb.Append("  PlayPactCreatorId: ").Append(PlayPactCreatorId).Append("\n");
            sb.Append("  PlayPactReportId: ").Append(PlayPactReportId).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  Rules: ").Append(Rules).Append("\n");
            sb.Append("  Evaluation: ").Append(Evaluation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
