/*
 * PlayPact API
 *
 * The API for PlayPact.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@playpact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PlayPact.OpenAPI.Client.OpenAPIDateConverter;

namespace PlayPact.OpenAPI.Model
{
    /// <summary>
    /// MyReportListDto
    /// </summary>
    [DataContract(Name = "MyReportListDto")]
    public partial class MyReportListDto : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets ReportStatus
        /// </summary>
        [DataMember(Name = "reportStatus", EmitDefaultValue = false)]
        public ReportStatus? ReportStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MyReportListDto" /> class.
        /// </summary>
        /// <param name="playPactReportId">playPactReportId.</param>
        /// <param name="accusation">accusation.</param>
        /// <param name="serverName">serverName.</param>
        /// <param name="subjectName">subjectName.</param>
        /// <param name="reportStatus">reportStatus.</param>
        public MyReportListDto(Guid playPactReportId = default(Guid), string accusation = default(string), string serverName = default(string), string subjectName = default(string), ReportStatus? reportStatus = default(ReportStatus?))
        {
            this.PlayPactReportId = playPactReportId;
            this.Accusation = accusation;
            this.ServerName = serverName;
            this.SubjectName = subjectName;
            this.ReportStatus = reportStatus;
        }

        /// <summary>
        /// Gets or Sets PlayPactReportId
        /// </summary>
        [DataMember(Name = "playPactReportId", EmitDefaultValue = false)]
        public Guid PlayPactReportId { get; set; }

        /// <summary>
        /// Gets or Sets Accusation
        /// </summary>
        [DataMember(Name = "accusation", EmitDefaultValue = true)]
        public string Accusation { get; set; }

        /// <summary>
        /// Gets or Sets ServerName
        /// </summary>
        [DataMember(Name = "serverName", EmitDefaultValue = true)]
        public string ServerName { get; set; }

        /// <summary>
        /// Gets or Sets SubjectName
        /// </summary>
        [DataMember(Name = "subjectName", EmitDefaultValue = true)]
        public string SubjectName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MyReportListDto {\n");
            sb.Append("  PlayPactReportId: ").Append(PlayPactReportId).Append("\n");
            sb.Append("  Accusation: ").Append(Accusation).Append("\n");
            sb.Append("  ServerName: ").Append(ServerName).Append("\n");
            sb.Append("  SubjectName: ").Append(SubjectName).Append("\n");
            sb.Append("  ReportStatus: ").Append(ReportStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
