/*
 * PlayPact API
 *
 * The API for PlayPact.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@playpact.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PlayPact.OpenAPI.Client.OpenAPIDateConverter;

namespace PlayPact.OpenAPI.Model
{
    /// <summary>
    /// Defines ReportStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ReportStatus
    {
        /// <summary>
        /// Enum Draft for value: Draft
        /// </summary>
        [EnumMember(Value = "Draft")]
        Draft = 1,

        /// <summary>
        /// Enum WaitingForObjection for value: WaitingForObjection
        /// </summary>
        [EnumMember(Value = "WaitingForObjection")]
        WaitingForObjection = 2,

        /// <summary>
        /// Enum OpenForReview for value: OpenForReview
        /// </summary>
        [EnumMember(Value = "OpenForReview")]
        OpenForReview = 3,

        /// <summary>
        /// Enum Confirmed for value: Confirmed
        /// </summary>
        [EnumMember(Value = "Confirmed")]
        Confirmed = 4,

        /// <summary>
        /// Enum Rejected for value: Rejected
        /// </summary>
        [EnumMember(Value = "Rejected")]
        Rejected = 5
    }

}
